export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_ITEM = 'DELETE_ITEM';
export const REQUEST_PRODUCT_DATA = 'REQUEST_PRODUCT_DATA';
export const RECEIVE_PRODUCT_DATA = 'RECEIVE_PRODUCT_DATA';
